version: "3.8"
services:
  rotate:
    image: python:3.10-slim
    volumes: [ ./:/opt/star-tigo-defensa ]
    working_dir: /opt/star-tigo-defensa
    environment:
      - ROT_KEY=${ROT_KEY}
      - ROT_INTERVAL=600
      - ROT_MODE=${ROT_MODE:-right}
    command: ["python3","rotate/rotate_service.py"]
  verify:
    image: python:3.10-slim
    volumes: [ ./:/opt/star-tigo-defensa ]
    environment: [ "ROT_KEY=${ROT_KEY}" ]
    command: ["python3","rotate/verify_loop.py"]
  repair:
    image: python:3.10-slim
    volumes: [ ./:/opt/star-tigo-defensa ]
    command: ["python3","repair/monitor_and_repair.py"]
  serve:
    image: python:3.10-slim
    volumes: [ ./:/opt/star-tigo-defensa ]
    ports: ["8080:8080"]
    environment: [ "ROT_KEY=${ROT_KEY}" ]
    command: ["python3","serve/loader_server.py"]
