version: "3.8"
services:
  rotate:
    image: python:3.10-slim
    container_name: rotate
    volumes:
      - ../:/opt/star-tigo-defensa
    working_dir: /opt/star-tigo-defensa/rotate
    environment:
      - ROT_KEY=${ROT_KEY}
      - ROT_INTERVAL=${ROT_INTERVAL:-600}
      - GIT_PUSH=${GIT_PUSH:-false}
      - GIT_REMOTE=${GIT_REMOTE:-origin}
      - ROT_MODE=${ROT_MODE:-right}
    command: ["python3","rotate_service.py"]
  verify:
    image: python:3.10-slim
    container_name: verify
    volumes:
      - ../:/opt/star-tigo-defensa
    working_dir: /opt/star-tigo-defensa/rotate
    environment:
      - ROT_KEY=${ROT_KEY}
    command: ["python3","verify_loop.py"]
  repair:
    image: python:3.10-slim
    container_name: repair
    volumes:
      - ../:/opt/star-tigo-defensa
    working_dir: /opt/star-tigo-defensa/repair
    command: ["python3","monitor_and_repair.py"]
  serve:
    image: python:3.10-slim
    container_name: serve
    volumes:
      - ../:/opt/star-tigo-defensa
    working_dir: /opt/star-tigo-defensa/serve
    ports:
      - "8080:8080"
    environment:
      - ROT_KEY=${ROT_KEY}
    command: ["python3","loader_server.py"]
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    ports:
      - "5001:5001"
      - "4001:4001"
    volumes:
      - ipfs_data:/data/ipfs
volumes:
  ipfs_data:
